### ISSUE TITLE
Sync default audio and mod audio

### ISSUE THREAD

**Issue by romek-rf** [rafalh/dashfaction#116]
ISSUE: When opening a mod, the audio is reset to 100 and can be extremely loud. Sync to whatever the player set the default audio.

Also, consider lowering the default Red Faction audio. It's louder than any other application.

**Comment by GooberRF** [comment]
I completely agree that the default audio level is way too loud. That said, I would be opposed to a sync between base game volume (in players.cfg) with default mod volume (players_MODNAME.cfg). Many people set base game music and message volume to 0%, which, if the volume with mods were synced, would result in them missing new content added by mods, likely without even realizing it.

I think just defaulting all 3 volume sliders in the base game and mod players.cfg files (by default) to 50% (as I mentioned in duplicate issue #172 ) rather than the current 100% is a solution that is both less likely to cause issues and much more simple to implement.
