### ISSUE TITLE
Rename "autosave.svl" to "autosav.svl"

### ISSUE THREAD

**Issue by Mystyled** [rafalh/dashfaction#177]
In the current development build of Dash, the autosaving feature outputs to `autosave.svl`. I believe the 'e' should be dropped for consistency with the existing `quicksav.svl`. Quick comparison below:

Autosave:
![Autosave](https://user-images.githubusercontent.com/89315313/174518783-3b8f6325-afd9-4709-8943-0d2c1600a35f.png)

Autosav:
![Autosav](https://user-images.githubusercontent.com/89315313/174518709-82d9092c-19af-4212-8d5c-110ce1e31f7a.png)

**Comment by mjr4077au** [comment]
It'd be like that from days gone by where you needed 8.3 filenames and LFN support wasn't guaranteed. I wouldn't change it though because it'll break existing autosaves.

**Comment by rafalh** [comment]
Quick save filename was (most likely) shortened to `quicksav.svl` to make it compatible with 8.3 format. `autosave.svl` is already 8.3 so I don't see much point in shortening it. Currently ending is not consistent but length is :) I don't really care what the name is so I am open for changing it but I would like to see more opinions.
> I wouldn't change it though because it'll break existing autosaves.
I don't think we need to worry about backward compatibility. The worst thing that can happen is people having 2 autosave files and it won't break anything except maybe confuse those people a little

**Comment by GooberRF** [comment]
Just to consolidate the opinions here for your reference rafalh since you said you'd like to see them - the author of this issue posed the question on the Discord support channel for feedback.

I said that I didn't think it really mattered much either way, but that I had a slight preference to leaving it as-is just to reduce confusion on the part of players who may have already compiled a Dash build and played through the game, creating autosave files, without realizing they'd then need to rename their latest autosave because the referenced filename changed.

Intharth raised the point that users could be more likely to confuse "quicksav" with "autosav" if the autosave file were renamed, and that the difference in naming format (ie. having an "e" at the end of autosave.svl) might help prevent that.

**Comment by rafalh** [comment]
I've seen that. Topic was discussed so I am closing the issue. Please feel free to open it again if any new information arrive.
