### ISSUE TITLE
Please add a command to display the date from the level file

### ISSUE THREAD

**Issue by natarii** [rafalh/dashfaction#238]
This information is displayed at the bottom of the screen upon level load, but this is easily missed. It would be nice to have a console command that would print it for the currently loaded level.

**Comment by is-this-c** [comment]
I think it would be useful if it prints the name and author along with the date.

**Comment by rafalh** [comment]
Would you prefer adding more information in `info` command or adding a new command like `level_info`?

**Comment by is-this-c** [comment]
A separate command keeps things succinct and `level_info` isn't too clear. I like `map_about`.

**Comment by GooberRF** [comment]
> Would you prefer adding more information in `info` command or adding a new command like `level_info`?

I never realized it before now, but apparently the `level_info` command already exists? Currently it only prints the rfl filename, but that would seem to be the most appropriate place to put this additional info.

Perhaps it's worth considering simply making this command print all the level info from the level properties panel in RED, rather than just name/author/date? Currently there is no way to display most of this info in-game, and it would be good to change that.

This is the info from level properties:
- Level name
- Author
- RFL save date
- Ambient light colour
- Fog colour, near clip, and far clip
- Level is outside/inside (a bool, I think?)
- Geomod crater texture
- Level hardness
- Multiplayer level bool

**Comment by rafalh** [comment]
I decided that for now filename+name+author+date is enough. Both names `map_info` and `level_info` are supported.
I didn't want to output all possible information about the level because it would make it less useful for normal people who don't care about fog color or level hardness and just want to check basic metadata.
All that more advanced information can be found in the editor if someone is interested.
